---
title: "Tract_School interpolation_Social Atlas"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
```

Read in the data. 
```{r}
tract_data<-read_csv("data/census_tractdata_acc.csv") %>%
  filter(substr(var,nchar(var)-1,nchar(var))!="_p" &
           var_type=="est" & 
           substr(GEOID,1,5)=="13059")

cw<-read_csv("data/ESzones_tract_crosswalk.csv") %>%
  rename(GEOID=TRACTID)

metadata<-read_csv("data/metadata_acsvars.csv")

rawdata_acc<-read_csv("data/ACS_data.csv") %>%
  filter(substr(GEOID,1,5)=="13059") %>%
  left_join(metadata) %>%
  filter(var_normalize=="99999") %>%
    select(GEOID,variable,estimate,var_name)

olddata<-st_read("data/AWP_shinydata.gpkg",layer="es_zones")
```

Join and interpolate the data
```{r}
cw_data<-tract_data %>%
  left_join(cw) %>%
  mutate(value_interp=value*POPRATIO) %>%
  group_by(var,SchoolID,School) %>%
  summarise(value=round(sum(value_interp),0)) %>%
  left_join(metadata %>%
              select(var_group,var_normalize) %>%
              rename(var=var_group))

cw_data_norm<-rawdata_acc %>%
  rename(value=estimate,
         var=var_name) %>%
  left_join(cw) %>%
  mutate(value_interp=value*POPRATIO) %>%
  group_by(var,SchoolID,School) %>%
  summarise(value_norm=round(sum(value_interp),0)) %>%
  rename(var_normalize=var)
```

Change to percentage

```{r}
metadata_group<-metadata %>%
  select(var_group,var_normalize) %>%
  rename(var=var_group)
  
#Join normalizing variables back and create a percentage
census_data_pct <- cw_data %>%
  left_join(cw_data_norm) %>%
  mutate(est_pct=round(value/value_norm*100,2)) %>%
  select(-var_normalize,-value_norm)
```

Prepare data for atlas
```{r}
census_data_atlas<-census_data_pct %>%
  left_join(metadata %>%
              select(var_group,desc_group) %>%
              rename(var=var_group,
                     description=desc_group)) %>%
  select(-value) %>%
  rename(est=est_pct) %>%
  distinct %>%
  left_join(olddata)

st_write(census_data_atlas,"data/AWP_shinydata.gpkg",layer="acsdata_2018")
```


