---
title: "Athens Social Atlas"
resource_files:
- ElementarySchoolDistricts_data.cpg
- ElementarySchoolDistricts_data.dbf
- ElementarySchoolDistricts_data.prj
- ElementarySchoolDistricts_data.qpj
- ElementarySchoolDistricts_data.shp
- ElementarySchoolDistricts_data.shx
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: cerulean
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(leaflet)
#library(rgdal)
library(RColorBrewer)
library(classInt)
library(highcharter)
library(plotly)
library(ggplot2)
#library(reshape2)
#library(readxl)
library(sf)
library(tidyverse)
#library(googlesheets)

#atlasgoogle<-gs_url("https://docs.google.com/spreadsheets/d/1ACdNruOZAI7jlzJ3RR49S788jtK1_1qSGWBXSumuLLg/edit?usp=sharing")
#atlasdata_wide<-gs_read(sheet,ws="Data")
#metadata<-gs_read(sheet,ws="Metadata")
#atlasdata<-melt(atlasdata_wide,id.vars=c("School","SchoolID"))

atlasdata<-read_csv("data/AthensSocialAtlasData_2018_02_05.csv")
atlasdata_wide<-atlasdata %>% 
  select(-moe) %>%
  spread(var,est) 
districts<-st_read("app_old/ElementarySchoolDistricts_data.shp") %>%
  select(SchoolID) %>%
  left_join(atlasdata_wide)
metadata<-read_csv("data/AthensSocialAtlasData_metadata_2018_02_05.csv")

```

Single issue
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

####Variable selection

```{r}
radioButtons("ngroups","Classify school zones into how many equally sized groups?",c(3, 4,5,6),selected=4)

radioButtons("group","Choose your variable domain:",
             c("Community Safety"="Safety",
               "Demographics"="Demog",
               "Healthy People & Environments"="Health",
               "Housing"="Housing",
               "Income & Employment" = "Income",
               "Lifelong Learning" = "Learning",
               "Transportation" = "Transport"),
             selected="Safety")

conditionalPanel(
 condition="input.group=='Safety'",
  selectInput("variable1","Select your variable:",
               c("Part I Crime Rate" = "P1CRIME_v",
                "Part II Crime Rate" = "P2CRIME_v",
                "Sexual Assault and Family Offense Rates" = "SAFO_v",
                "Crime Clearance Percentage" = "CRIMECLE_v",
                "Traffic Accidents" = "ACCMILE_v",
                "Pedestrian/Bicycle Accidents" = "PBA10M_v",
                "Sidewalks" = "SIDEWALK_v",
                "Streetlights" = "L1000_v",
                "Driveways per Household" = "DRIVEWAY_v",
                "Violent Referrals" = "VIOL_REF_v",
                "Domestic Crime Rates" = "DOMCRIME_v")
               )
)

conditionalPanel(
 condition="input.group=='Demog'",
  selectInput("variable2","Select your variable:",
               c("Total population" = "TOTALPOP_v",
                 "Population of White Americans" = "POPWHITE_v",
                 "% White Americans" = "PERWHITE_v",
                 "Population of African Americans" = "POPAFAM_v",
                 "% African Americans" = "PERAFAM_v",
                 "Population of Asian Americans" = "POPASAM_v",
                 "% Asian Americans" = "PERASAM_v",
                 "Population of Hispanic/Latino" = "POPHISP_v",
                 "% Hispanic/Latino" = "PERHISP_v",
                 "Population under 18" = "POP18_v",
                 "% Population under 18" = "PER18_v",
                 "Population 18-24" = "POP1824_v",
                 "% Population 18-24" = "PER1824_v",
                 "Population above 65" = "POP65_v",
                 "% Population above 65" = "PER65_v",
                 "Population in poverty under 18" = "POPPOV18_v",
                 "% Population in poverty under 18" = "PERPOV18_v",
                 "Population in poverty above 65" = "POPPOV65_v",
                 "% Population in poverty above 65" = "PERPOV65_v")
               )
)

conditionalPanel(
 condition="input.group=='Health'",
  selectInput("variable3","Select your variable:",
              c("3+ Chronic Health Issues" = "PER3CHRO_v",
                "Barriers to Health Care Access" = "PERBARRI_v",
                "Inability to Afford Health Care Access" = "PERAFFOR_v",
                "Uninsured " = "PERUNINS_v",
                "Avian Species Richness" = "AVAIANSP_v",
                "Green Space" = "PERGREEN_v",
                "Impaired Streams" = "PERIMSTR_v",
                "Toxic Release Inventory Sites" = "NUMTOXIC_v",
                "Conservation Easement" = "PERCONSE_v",
                "Food Pantries" = "NUMFOODP_v",
                "School Gardens" = "NUMSGARD_v",
                "Community Gardens" = "NUMCOMGAR_v")
)
)

conditionalPanel(
 condition="input.group=='Housing'",
  selectInput("variable4","Select your variable:",
              c("Housing Units" = "H_UNIT_v",
                "Households" = "HHOLDS_v",
                "Percent Occupied" = "PEROCC_v",
                "Percent Vacant" = "PERVAC_v",
                "Percent Owner Occupied" = "PEROOCC_v",
                "Percent Renter Occupied" = "PERROCC_v",
                "Rent: Overburdened Households" = "PERHH30_v",
                "Mean Home Value" = "MEANHVAL_v",
                "Lead Exposure Risk" = "LEADRISK_v")
)
)

conditionalPanel(
 condition="input.group=='Income'",
  selectInput("variable5","Select your variable:",
              c("Percent Unemployment" = "PERUNEMP_v",
                "Gini Index" = "GINI_v",
                "Number of Houses with Income of <$10,000" = "INCUN10_v",
                "# of Houses w/ Income $10-20,000" = "INC1020_v",
                "# of Houses w/ Income $20-30,000" = "INC2030_v",
                "# of Houses w/ Income $30-50,000" = "INC3050_v",
                "# of Houses w/ Income $50-75,000" = "INC5075_v",
                "# of Houses w/ Income $75-100,000" = "INC75100_v",
                "# of Houses w/ Income $100,000-199,999" = "INC1_199_v",
                "# of Houses w/ Income $200,000+" = "INC200_v",
                "Agriculture (002) # of Workers Per District" = "AGR_DIS_v",
                "Construction (003)" = "CON_DIS_v",
                "Manufacturing (004)" = "MANU_DIS_v",
                "Transportation and Warehousing (007)" = "TRAN_DIS_v",
                "Public Administration (014)" = "PADM_DIS_v",
                "Professional, Scientific, Management (010) " = "PSM_DIS_v",
                "Information (008)" = "INFO_DIS_v",
                "Finance (009)" = "FINA_DIS_v",
                "Other Services (013)" = "OTH_DIS_v",
                "Education and Healthcare (011)" = "EDU_DIS_v",
                "Arts, Entertainment, Recreation (012)" = "ART_DIS_v",
                "Wholesale Trade (006)" = "WHOL_DIS_v")
)
)


conditionalPanel(
 condition="input.group=='Learning'",
  selectInput("variable6","Select your variable:",
              c("Population Under 5" = "PER5_v",
                "Enrollment of Preschool/Nursery" = "PERPRES_v",
                "Pop. without HS Diploma" = "PER12TH_v",
                "Enrollment in Undergraduate School" = "PERUNDG_v",
                "Enrollment in Graduate School" = "PERGRAD_v",
                "Attainment: Some College" = "PERSOMEC_v",
                "Attainment: Bachelor's or Higher Over 25" = "PERBACH_v",
                "Within 1 Mile of Pre-K/Nursery" = "PER1MPRE_v",
                "Within 3 Miles of Pre-K/Nursery" = "PER3MPRE_v",
                "Elementary Attendance Rates" = "ELATTEND_v",
                "Elementary Teacher Years of Experience" = "EYEAREXP_v",
                "Elemantary Average Class Size" = "ELCSIZE_v",
                "Elementary Student-Teacher Ratio" = "ESTRATIO_v")
)
)

conditionalPanel(
 condition="input.group=='Transport'",
  selectInput("variable7","Select your variable:",
              c("% Commuting by Car" = "PERCAR_v",
                "Commuting by Bike" = "PERBIKE_v",
                "Commuting by Public Transit" = "PERBUS_v",
                "Commuting by Walking" = "PERWALK_v",
                "Crashes per 1000 residents" = "CCRASH_v",
                "Public Sidewalk to Road Ratio" = "R_SROAD_v",
                "Public Sidewalk Area per person" = "R_SPERS_v",
                "Households with No Vehicle" = "NOVEH_v",
                "Transportation Vulnerability Index" = "TVULNER_v",
                "Roads with Bike Lanes" = "BROADS_v",
                "ACC Bus Service Area Coverage" = "BUSZONE_v")
)
)

#Use the variable object to select the variable people choose
variable<-reactive({
    if(input$group=="Safety"){
    input$variable1
  } else if (input$group=="Demog") {
    input$variable2
  } else if (input$group=="Health") {
    input$variable3
  } else if (input$group=="Housing") {
    input$variable4
  } else if (input$group=="Income") {
    input$variable5
  } else if (input$group=="Learning") {
    input$variable6
  } else if (input$group=="Transport") {
    input$variable7 }
  })

```

Column {data-width=450}
-----------------------------------------------------------------------
```{r fig.height=10}
#Text box from the metadata file that shows what variable has been selected
filter_metadata<-reactive({
    metadata[metadata$var_val==variable(),]
  })

output$text<-renderUI(
  HTML(paste("<b>Variable name: </b>",filter_metadata()$description,
             "<br><b>Source: </b>",filter_metadata()$source,"<br><br>",sep=""))
)

htmlOutput("text")
```

###Click on a school zone for more information.

```{r}
#Create the variable to be mapped.
#Right now this is subsetted from a shapefile that had all the data.
#Now I'd prefer you do a leftjoin with the csv data to a geojson file that just has school ID.
filteredData_variable<-reactive({
  dist<-districts %>%
    select(ES_short)
  dist
})



##Need to create popup with school name and variable value

output$map <- renderLeaflet({
  
  nclassint=as.numeric(input$ngroups)

  pal1<-colorQuantile(palette = "Reds", domain = filteredData_variable()$variable_dist,n=nclassint)
  
  popup<-paste("<b>School zone: </b>",filteredData_variable()$ES_short,"<br>",
                    "<b>Variable value:</b> ",filteredData_variable()$variable_dist,
                    sep="")
  
leaflet(filteredData_variable()) %>% 
  setView(lng = -83.3776, lat = 33.94, zoom = 11)%>%
  addProviderTiles("CartoDB.Positron",
                   options = providerTileOptions(noWrap = TRUE)) %>%
  addPolygons(fillOpacity=.6,
              fillColor=~pal1(variable_dist),
              weight=1,
              color="#222222",
              popup=popup) %>%
  addLegend(position="bottomright",
            pal = pal1, 
            title="Legend",
            values = ~variable_dist, 
            labFormat = function(type, cuts, p) {
                n = length(cuts)
                paste0(cuts[-n], " &ndash; ", cuts[-1])})
})

leafletOutput('map',height="3000px")
                  

```

Column {.tabset data-width=300}
-----------------------------------------------------------------------
### Chart

```{r}



data.chart<-reactive({
    data.chart1<-atlasdata[atlasdata$variable==variable(),]
    #data.chart<-data.chart1[order(-data.chart1$value),]
    
   if(input$chart_sort1=="School"){
   data.chart1<-data.chart1[order(data.chart1$School),]
   } else if (input$chart_sort1=="Variable_hl"){
     data.chart1<-data.chart1[order(-data.chart1$value),]
   } else if (input$chart_sort1=="Variable_lh"){
     data.chart1<-data.chart1[order(data.chart1$value),]
   }
    
    data.chart1
})

output$highchart<-renderHighchart(
  
  hchart(data.chart(),"bar",x=School,y=value) %>% 
    hc_add_theme(hc_theme_gridlight()) %>%
    hc_colors("#bd0026") %>%
    hc_yAxis(title = list(text = "Variable value"))
)


fillCol(height="80%",flex=c(.08,1),
      radioButtons("chart_sort1","Sort the chart by what criteria?",
            c("School name"="School",
              "Variable (high->low)"="Variable_hl",
              "Variable (low->high)"="Variable_lh"),inline=TRUE),
highchartOutput('highchart')
)

```

### Table

Values for this variable by school zone. Click on "Value" to sort.

```{r}
output$table<-renderDataTable(
    atlasdata[atlasdata$variable==variable(),c(1,4)],
  options=list(paging=FALSE,searching=FALSE)
)

dataTableOutput('table')
```









Two issues
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

####Variable selection

```{r}
selectInput("ngroups1","Classify school zones into how many equally sized groups?",c(3, 4,5,6),selected=4)



#sliderInput("mapheight","Map height",min=400,max=1200,value=600)

```

**Variable 1:**
```{r}
selectInput("group1","Choose your variable domain:",
             c("Community Safety"="Safety",
               "Demographics"="Demog",
               "Healthy People & Environments"="Health",
               "Housing"="Housing",
               "Income & Employment" = "Income",
               "Lifelong Learning" = "Learning",
               "Transportation" = "Transport"),
             selected="Safety")

conditionalPanel(
 condition="input.group1=='Safety'",
  selectInput("variable1.1","Select your variable:",
               c("Part I Crime Rate" = "P1CRIME_v",
                "Part II Crime Rate" = "P2CRIME_v",
                "Sexual Assault and Family Offense Rates" = "SAFO_v",
                "Crime Clearance Percentage" = "CRIMECLE_v",
                "Traffic Accidents" = "ACCMILE_v",
                "Pedestrian/Bicycle Accidents" = "PBA10M_v",
                "Sidewalks" = "SIDEWALK_v",
                "Streetlights" = "L1000_v",
                "Driveways per Household" = "DRIVEWAY_v",
                "Violent Referrals" = "VIOL_REF_v",
                "Domestic Crime Rates" = "DOMCRIME_v")
               )
)

conditionalPanel(
 condition="input.group1=='Demog'",
  selectInput("variable2.1","Select your variable:",
               c("Total population" = "TOTALPOP_v",
                 "Population of White Americans" = "POPWHITE_v",
                 "% White Americans" = "PERWHITE_v",
                 "Population of African Americans" = "POPAFAM_v",
                 "% African Americans" = "PERAFAM_v",
                 "Population of Asian Americans" = "POPASAM_v",
                 "% Asian Americans" = "PERASAM_v",
                 "Population of Hispanic/Latino" = "POPHISP_v",
                 "% Hispanic/Latino" = "PERHISP_v",
                 "Population under 18" = "POP18_v",
                 "% Population under 18" = "PER18_v",
                 "Population 18-24" = "POP1824_v",
                 "% Population 18-24" = "PER1824_v",
                 "Population above 65" = "POP65_v",
                 "% Population above 65" = "PER65_v",
                 "Population in poverty under 18" = "POPPOV18_v",
                 "% Population in poverty under 18" = "PERPOV18_v",
                 "Population in poverty above 65" = "POPPOV65_v",
                 "% Population in poverty above 65" = "PERPOV65_v")
               )
)

conditionalPanel(
 condition="input.group1=='Health'",
  selectInput("variable3.1","Select your variable:",
              c("3+ Chronic Health Issues" = "PER3CHRO_v",
                "Barriers to Health Care Access" = "PERBARRI_v",
                "Inability to Afford Health Care Access" = "PERAFFOR_v",
                "Uninsured " = "PERUNINS_v",
                "Avian Species Richness" = "AVAIANSP_v",
                "Green Space" = "PERGREEN_v",
                "Impaired Streams" = "PERIMSTR_v",
                "Toxic Release Inventory Sites" = "NUMTOXIC_v",
                "Conservation Easement" = "PERCONSE_v",
                "Food Pantries" = "NUMFOODP_v",
                "School Gardens" = "NUMSGARD_v",
                "Community Gardens" = "NUMCOMGAR_v")
)
)

conditionalPanel(
 condition="input.group1=='Housing'",
  selectInput("variable4.1","Select your variable:",
              c("Housing Units" = "H_UNIT_v",
                "Households" = "HHOLDS_v",
                "Percent Occupied" = "PEROCC_v",
                "Percent Vacant" = "PERVAC_v",
                "Percent Owner Occupied" = "PEROOCC_v",
                "Percent Renter Occupied" = "PERROCC_v",
                "Rent: Overburdened Households" = "PERHH30_v",
                "Mean Home Value" = "MEANHVAL_v",
                "Lead Exposure Risk" = "LEADRISK_v")
)
)

conditionalPanel(
 condition="input.group1=='Income'",
  selectInput("variable5.1","Select your variable:",
              c("Percent Unemployment" = "PERUNEMP_v",
                "Gini Index" = "GINI_v",
                "Number of Houses with Income of <$10,000" = "INCUN10_v",
                "# of Houses w/ Income $10-20,000" = "INC1020_v",
                "# of Houses w/ Income $20-30,000" = "INC2030_v",
                "# of Houses w/ Income $30-50,000" = "INC3050_v",
                "# of Houses w/ Income $50-75,000" = "INC5075_v",
                "# of Houses w/ Income $75-100,000" = "INC75100_v",
                "# of Houses w/ Income $100,000-199,999" = "INC1_199_v",
                "# of Houses w/ Income $200,000+" = "INC200_v",
                "Agriculture (002) # of Workers Per District" = "AGR_DIS_v",
                "Construction (003)" = "CON_DIS_v",
                "Manufacturing (004)" = "MANU_DIS_v",
                "Transportation and Warehousing (007)" = "TRAN_DIS_v",
                "Public Administration (014)" = "PADM_DIS_v",
                "Professional, Scientific, Management (010) " = "PSM_DIS_v",
                "Information (008)" = "INFO_DIS_v",
                "Finance (009)" = "FINA_DIS_v",
                "Other Services (013)" = "OTH_DIS_v",
                "Education and Healthcare (011)" = "EDU_DIS_v",
                "Arts, Entertainment, Recreation (012)" = "ART_DIS_v",
                "Wholesale Trade (006)" = "WHOL_DIS_v")
)
)


conditionalPanel(
 condition="input.group1=='Learning'",
  selectInput("variable6.1","Select your variable:",
              c("Population Under 5" = "PER5_v",
                "Enrollment of Preschool/Nursery" = "PERPRES_v",
                "Pop. without HS Diploma" = "PER12TH_v",
                "Enrollment in Undergraduate School" = "PERUNDG_v",
                "Enrollment in Graduate School" = "PERGRAD_v",
                "Attainment: Some College" = "PERSOMEC_v",
                "Attainment: Bachelor's or Higher Over 25" = "PERBACH_v",
                "Within 1 Mile of Pre-K/Nursery" = "PER1MPRE_v",
                "Within 3 Miles of Pre-K/Nursery" = "PER3MPRE_v",
                "Elementary Attendance Rates" = "ELATTEND_v",
                "Elementary Teacher Years of Experience" = "EYEAREXP_v",
                "Elemantary Average Class Size" = "ELCSIZE_v",
                "Elementary Student-Teacher Ratio" = "ESTRATIO_v")
)
)

conditionalPanel(
 condition="input.group1=='Transport'",
  selectInput("variable7.1","Select your variable:",
              c("% Commuting by Car" = "PERCAR_v",
                "Commuting by Bike" = "PERBIKE_v",
                "Commuting by Public Transit" = "PERBUS_v",
                "Commuting by Walking" = "PERWALK_v",
                "Crashes per 1000 residents" = "CCRASH_v",
                "Public Sidewalk to Road Ratio" = "R_SROAD_v",
                "Public Sidewalk Area per person" = "R_SPERS_v",
                "Households with No Vehicle" = "NOVEH_v",
                "Transportation Vulnerability Index" = "TVULNER_v",
                "Roads with Bike Lanes" = "BROADS_v",
                "ACC Bus Service Area Coverage" = "BUSZONE_v")
)
)

variable1<-reactive({
    if(input$group1=="Safety"){
    input$variable1.1
  } else if (input$group1=="Demog") {
    input$variable2.1
  } else if (input$group1=="Health") {
    input$variable3.1
  } else if (input$group1=="Housing") {
    input$variable4.1
  } else if (input$group1=="Income") {
    input$variable5.1
  } else if (input$group1=="Learning") {
    input$variable6.1
  } else if (input$group1=="Transport") {
    input$variable7.1 }
  })

```

**Variable 2:**
```{r}
selectInput("group2","Choose your variable domain:",
             c("Community Safety"="Safety",
               "Demographics"="Demog",
               "Healthy People & Environments"="Health",
               "Housing"="Housing",
               "Income & Employment" = "Income",
               "Lifelong Learning" = "Learning",
               "Transportation" = "Transport"),
             selected="Safety")

conditionalPanel(
 condition="input.group2=='Safety'",
  selectInput("variable1.2","Select your variable:",
               c("Part I Crime Rate" = "P1CRIME_v",
                "Part II Crime Rate" = "P2CRIME_v",
                "Sexual Assault and Family Offense Rates" = "SAFO_v",
                "Crime Clearance Percentage" = "CRIMECLE_v",
                "Traffic Accidents" = "ACCMILE_v",
                "Pedestrian/Bicycle Accidents" = "PBA10M_v",
                "Sidewalks" = "SIDEWALK_v",
                "Streetlights" = "L1000_v",
                "Driveways per Household" = "DRIVEWAY_v",
                "Violent Referrals" = "VIOL_REF_v",
                "Domestic Crime Rates" = "DOMCRIME_v")
               )
)

conditionalPanel(
 condition="input.group2=='Demog'",
  selectInput("variable2.2","Select your variable:",
               c("Total population" = "TOTALPOP_v",
                 "Population of White Americans" = "POPWHITE_v",
                 "% White Americans" = "PERWHITE_v",
                 "Population of African Americans" = "POPAFAM_v",
                 "% African Americans" = "PERAFAM_v",
                 "Population of Asian Americans" = "POPASAM_v",
                 "% Asian Americans" = "PERASAM_v",
                 "Population of Hispanic/Latino" = "POPHISP_v",
                 "% Hispanic/Latino" = "PERHISP_v",
                 "Population under 18" = "POP18_v",
                 "% Population under 18" = "PER18_v",
                 "Population 18-24" = "POP1824_v",
                 "% Population 18-24" = "PER1824_v",
                 "Population above 65" = "POP65_v",
                 "% Population above 65" = "PER65_v",
                 "Population in poverty under 18" = "POPPOV18_v",
                 "% Population in poverty under 18" = "PERPOV18_v",
                 "Population in poverty above 65" = "POPPOV65_v",
                 "% Population in poverty above 65" = "PERPOV65_v")
               )
)

conditionalPanel(
 condition="input.group2=='Health'",
  selectInput("variable3.2","Select your variable:",
              c("3+ Chronic Health Issues" = "PER3CHRO_v",
                "Barriers to Health Care Access" = "PERBARRI_v",
                "Inability to Afford Health Care Access" = "PERAFFOR_v",
                "Uninsured " = "PERUNINS_v",
                "Avian Species Richness" = "AVAIANSP_v",
                "Green Space" = "PERGREEN_v",
                "Impaired Streams" = "PERIMSTR_v",
                "Toxic Release Inventory Sites" = "NUMTOXIC_v",
                "Conservation Easement" = "PERCONSE_v",
                "Food Pantries" = "NUMFOODP_v",
                "School Gardens" = "NUMSGARD_v",
                "Community Gardens" = "NUMCOMGAR_v")
)
)

conditionalPanel(
 condition="input.group2=='Housing'",
  selectInput("variable4.2","Select your variable:",
              c("Housing Units" = "H_UNIT_v",
                "Households" = "HHOLDS_v",
                "Percent Occupied" = "PEROCC_v",
                "Percent Vacant" = "PERVAC_v",
                "Percent Owner Occupied" = "PEROOCC_v",
                "Percent Renter Occupied" = "PERROCC_v",
                "Rent: Overburdened Households" = "PERHH30_v",
                "Mean Home Value" = "MEANHVAL_v",
                "Lead Exposure Risk" = "LEADRISK_v")
)
)

conditionalPanel(
 condition="input.group2=='Income'",
  selectInput("variable5.2","Select your variable:",
              c("Percent Unemployment" = "PERUNEMP_v",
                "Gini Index" = "GINI_v",
                "Number of Houses with Income of <$10,000" = "INCUN10_v",
                "# of Houses w/ Income $10-20,000" = "INC1020_v",
                "# of Houses w/ Income $20-30,000" = "INC2030_v",
                "# of Houses w/ Income $30-50,000" = "INC3050_v",
                "# of Houses w/ Income $50-75,000" = "INC5075_v",
                "# of Houses w/ Income $75-100,000" = "INC75100_v",
                "# of Houses w/ Income $100,000-199,999" = "INC1_199_v",
                "# of Houses w/ Income $200,000+" = "INC200_v",
                "Agriculture (002) # of Workers Per District" = "AGR_DIS_v",
                "Construction (003)" = "CON_DIS_v",
                "Manufacturing (004)" = "MANU_DIS_v",
                "Transportation and Warehousing (007)" = "TRAN_DIS_v",
                "Public Administration (014)" = "PADM_DIS_v",
                "Professional, Scientific, Management (010) " = "PSM_DIS_v",
                "Information (008)" = "INFO_DIS_v",
                "Finance (009)" = "FINA_DIS_v",
                "Other Services (013)" = "OTH_DIS_v",
                "Education and Healthcare (011)" = "EDU_DIS_v",
                "Arts, Entertainment, Recreation (012)" = "ART_DIS_v",
                "Wholesale Trade (006)" = "WHOL_DIS_v")
)
)


conditionalPanel(
 condition="input.group2=='Learning'",
  selectInput("variable6.2","Select your variable:",
              c("Population Under 5" = "PER5_v",
                "Enrollment of Preschool/Nursery" = "PERPRES_v",
                "Pop. without HS Diploma" = "PER12TH_v",
                "Enrollment in Undergraduate School" = "PERUNDG_v",
                "Enrollment in Graduate School" = "PERGRAD_v",
                "Attainment: Some College" = "PERSOMEC_v",
                "Attainment: Bachelor's or Higher Over 25" = "PERBACH_v",
                "Within 1 Mile of Pre-K/Nursery" = "PER1MPRE_v",
                "Within 3 Miles of Pre-K/Nursery" = "PER3MPRE_v",
                "Elementary Attendance Rates" = "ELATTEND_v",
                "Elementary Teacher Years of Experience" = "EYEAREXP_v",
                "Elemantary Average Class Size" = "ELCSIZE_v",
                "Elementary Student-Teacher Ratio" = "ESTRATIO_v")
)
)

conditionalPanel(
 condition="input.group2=='Transport'",
  selectInput("variable7.2","Select your variable:",
              c("% Commuting by Car" = "PERCAR_v",
                "Commuting by Bike" = "PERBIKE_v",
                "Commuting by Public Transit" = "PERBUS_v",
                "Commuting by Walking" = "PERWALK_v",
                "Crashes per 1000 residents" = "CCRASH_v",
                "Public Sidewalk to Road Ratio" = "R_SROAD_v",
                "Public Sidewalk Area per person" = "R_SPERS_v",
                "Households with No Vehicle" = "NOVEH_v",
                "Transportation Vulnerability Index" = "TVULNER_v",
                "Roads with Bike Lanes" = "BROADS_v",
                "ACC Bus Service Area Coverage" = "BUSZONE_v")
)
)

variable2<-reactive({
    if(input$group2=="Safety"){
    input$variable1.2
  } else if (input$group2=="Demog") {
    input$variable2.2
  } else if (input$group2=="Health") {
    input$variable3.2
  } else if (input$group2=="Housing") {
    input$variable4.2
  } else if (input$group2=="Income") {
    input$variable5.2
  } else if (input$group2=="Learning") {
    input$variable6.2
  } else if (input$group2=="Transport") {
    input$variable7.2 }
  })


```

Column {data-width=450}
-----------------------------------------------------------------------
**Click on the map for more information.**
```{r}
    filter_metadata1<-reactive({
    metadata[metadata$var_val==variable1(),]
    })

output$text1<-renderUI(
  HTML(paste("<b>Variable Name: </b>",filter_metadata1()$description,
             "<br><b>Source: </b>",filter_metadata1()$source,"<br><br>",sep=""))
)

filteredData_variable1<-reactive({
  dist<-subset(districts,select=c("ES_short",variable1()))
  names(dist)<-c("ES_short","variable_dist")
  dist
})


output$map1 <- renderLeaflet({

  nclassint=as.numeric(input$ngroups1)

  pal1<-colorQuantile(palette = "Reds", domain = filteredData_variable1()$variable_dist,n=nclassint)

  popup<-paste("<b>School zone: </b>",filteredData_variable1()$ES_short,"<br>",
                    "<b>Variable value:</b> ",filteredData_variable1()$variable_dist,
                    sep="")

leaflet(filteredData_variable1()) %>%
  setView(lng = -83.3776, lat = 33.94, zoom = 11)%>%
  addProviderTiles("CartoDB.Positron",
                   options = providerTileOptions(noWrap = TRUE)) %>%
  addPolygons(fillOpacity=.6,
              fillColor=~pal1(variable_dist),
              weight=1,
              color="#222222",
              popup=popup) %>%
  addLegend(position="bottomright",
            pal = pal1,
            title="Legend",
            values = ~variable_dist,
            labFormat = function(type, cuts, p) {
                n = length(cuts)
                paste0(cuts[-n], " &ndash; ", cuts[-1])})
})

filter_metadata2<-reactive({
    metadata[metadata$var_val==variable2(),]
    })

output$text2<-renderUI(
  HTML(paste("<b>Variable Name: </b>",filter_metadata2()$description,
             "<br><b>Source: </b>",filter_metadata2()$source,"<br><br>",sep="")))



filteredData_variable2<-reactive({
  dist<-subset(districts,select=c("ES_short",variable2()))
  names(dist)<-c("ES_short","variable_dist")
  dist
})

output$map2 <- renderLeaflet({
  
  nclassint=as.numeric(input$ngroups1)

  pal2<-colorQuantile(palette = "Greens", domain = filteredData_variable2()$variable_dist,n=nclassint)

  popup<-paste("<b>School zone: </b>",filteredData_variable2()$ES_short,"<br>",
                    "<b>Variable value:</b> ",filteredData_variable2()$variable_dist,
                    sep="")

leaflet(filteredData_variable2()) %>%
  setView(lng = -83.3776, lat = 33.94, zoom = 11)%>%
  addProviderTiles("CartoDB.Positron",
                   options = providerTileOptions(noWrap = TRUE)) %>%
  addPolygons(fillOpacity=.6,
              fillColor=~pal2(variable_dist),
              weight=1,
              color="#222222",
              popup=popup) %>%
  addLegend(position="bottomright",
            pal = pal2,
            title="Legend",
            values = ~variable_dist,
            labFormat = function(type, cuts, p) {
                n = length(cuts)
                paste0(cuts[-n], " &ndash; ", cuts[-1])})
})


htmlOutput("text1", height=50)
leafletOutput('map1',height=600)
htmlOutput("text2", height=50)
leafletOutput('map2',height=600)                 


```

Column {.tabset data-width=300}
-----------------------------------------------------------------------
### Chart

```{r}


data.chart1<-reactive({
  table1<-atlasdata[atlasdata$variable==variable1(),c(1,4)]

   table2<-atlasdata[atlasdata$variable==variable2(),c(1,4)]
   
   tablemerge<-merge(table1,table2,by="School")
   names(tablemerge)<-c("School","Variable1","Variable2")
   
   if(input$chart_sort=="School"){
   tablemerge<-tablemerge[order(tablemerge$School),]
   } else if (input$chart_sort=="Variable1"){
     tablemerge<-tablemerge[order(-tablemerge$Variable1),]
   } else if (input$chart_sort=="Variable2"){
     tablemerge<-tablemerge[order(-tablemerge$Variable2),]
   }
   
   tablemerge
})

output$highchart1<-renderHighchart(
  hchart(data.chart1(),"bar",x=School,y=Variable1) %>%
    hc_add_theme(hc_theme_gridlight()) %>%
    hc_colors(c("#bd0026")) %>%
    hc_yAxis(title = list(text = "Variable 1 value"))
)
output$highchart2<-renderHighchart(
  hchart(data.chart1(),"bar",x=School,y=Variable2) %>%
    hc_add_theme(hc_theme_gridlight()) %>%
    hc_colors(c("#006d2c")) %>%
    hc_yAxis(title = list(text = "Variable 2 value"))
)

fillCol(height="80%",flex=c(.15,1,1),
        radioButtons("chart_sort","Sort the chart by what criteria?",
            c("School name"="School",
              "Variable 1"="Variable1",
              "Variable 2"="Variable2"),inline=TRUE),
highchartOutput('highchart1'),
highchartOutput('highchart2')
)

```

### Scatterplot
Mouse over points to see school name and values.
```{r}
tables1<-reactive({
   table1<-atlasdata[atlasdata$variable==variable1(),c(1,4)]

   table2<-atlasdata[atlasdata$variable==variable2(),c(1,4)]
   
   tablemerge<-merge(table1,table2,by="School")
   names(tablemerge)<-c("School","Variable1","Variable2")
   tablemerge
})

output$chart3<-renderPlotly({
  chart<-ggplot(tables1(),aes(x=Variable1,y=Variable2))+
    geom_point(aes(text=School))+
    stat_smooth()
  chartly<-ggplotly(chart)
  chartly
})

plotlyOutput('chart3')

```

### Table

Values for this variable by school zone. Click on "Value" to sort.

```{r}

tables2<-reactive({
   table1<-atlasdata[atlasdata$variable==variable1(),c(1,4)]

   table2<-atlasdata[atlasdata$variable==variable2(),c(1,4)]
   
   tablemerge<-merge(table1,table2,by="School")
   names(tablemerge)<-c("School","Variable 1","Variable 2")
   tablemerge
})

output$table_compare<-renderDataTable(
   tables2(),
   options=list(paging=FALSE,searching=FALSE)
)

dataTableOutput('table_compare')
```

